/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ui.garment.DisplayGarment;
import ui.student.AddStudentForm;
import ui.student.DisplayStudent;

/**
 *
 * @author jpainam
 */
public final class GUI extends javax.swing.JFrame {
    public static volatile GUI instance = null;
  
    public static GUI getInstance(){
        if(GUI.instance == null){
            synchronized(GUI.class){
                if(GUI.instance == null)
                    GUI.instance = new GUI();
            }
        }
        return GUI.instance;
    }
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jmenuBar = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmAccount = new javax.swing.JMenu();
        jmDisplayAccount = new javax.swing.JMenuItem();
        jmAddAccount = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jmEdit = new javax.swing.JMenu();
        jmDisplayEmployee = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmAddStudent = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmAddLeave = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dry cleaning 1.0");
        setBounds(new java.awt.Rectangle(200, 50, 700, 300));
        setPreferredSize(new java.awt.Dimension(835, 550));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jmFile.setText("File");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/connect.png"))); // NOI18N
        jMenuItem7.setText("Connect");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jmFile.add(jMenuItem7);
        jmFile.add(jSeparator3);

        jmAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/account.png"))); // NOI18N
        jmAccount.setText("Account");

        jmDisplayAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/display_account.png"))); // NOI18N
        jmDisplayAccount.setText("Display Account");
        jmAccount.add(jmDisplayAccount);

        jmAddAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_account.png"))); // NOI18N
        jmAddAccount.setText("Add Account");
        jmAccount.add(jmAddAccount);

        jmFile.add(jmAccount);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        jMenuItem8.setText("Exit");
        jmFile.add(jMenuItem8);

        jmenuBar.add(jmFile);

        jmEdit.setText("List");

        jmDisplayEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/display_student.png"))); // NOI18N
        jmDisplayEmployee.setText("Students");
        jmDisplayEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDisplayEmployeeActionPerformed(evt);
            }
        });
        jmEdit.add(jmDisplayEmployee);
        jmEdit.add(jSeparator2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/display_leave.png"))); // NOI18N
        jMenuItem3.setText("Leave");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmEdit.add(jMenuItem3);

        jmenuBar.add(jmEdit);

        jMenu1.setText("Add");

        jmAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student_add.png"))); // NOI18N
        jmAddStudent.setText("Student");
        jmAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAddStudentActionPerformed(evt);
            }
        });
        jMenu1.add(jmAddStudent);
        jMenu1.add(jSeparator4);

        jmAddLeave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_account.png"))); // NOI18N
        jmAddLeave.setText("Leave");
        jmAddLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAddLeaveActionPerformed(evt);
            }
        });
        jMenu1.add(jmAddLeave);

        jmenuBar.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/help.png"))); // NOI18N
        jMenuItem9.setText("Help");
        jMenu2.add(jMenuItem9);
        jMenu2.add(jSeparator1);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/aboutus.png"))); // NOI18N
        jMenuItem10.setText("About us");
        jMenuItem10.setToolTipText("Form about us");
        jMenu2.add(jMenuItem10);

        jmenuBar.add(jMenu2);

        setJMenuBar(jmenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAddLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAddLeaveActionPerformed
        try{
            //JOptionPane.showMessageDialog(null, "Ceci est le clic");
            this.setContentPane(new AddStudentForm());
            this.repaint();
            this.pack();
            //JOptionPane.showMessageDialog(null, "Ceci est le clic");
        }catch(IllegalStateException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jmAddLeaveActionPerformed

    private void jmDisplayEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDisplayEmployeeActionPerformed
        try{
            //JOptionPane.showMessageDialog(null, "Ceci est le clic");
            this.setContentPane(new DisplayStudent());
            this.repaint();
            this.pack();
            //JOptionPane.showMessageDialog(null, "Ceci est le clic");
        }catch(IllegalStateException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jmDisplayEmployeeActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try{
            this.getContentPane().removeAll();
            this.setContentPane(new DisplayGarment());
            this.repaint();
            this.pack();
        }catch(IllegalStateException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jmAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAddStudentActionPerformed
        try{
            this.getContentPane().removeAll();
            this.setContentPane(new AddStudentForm());
            this.repaint();
            this.pack();
        }catch(IllegalStateException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jmAddStudentActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu jmAccount;
    private javax.swing.JMenuItem jmAddAccount;
    private javax.swing.JMenuItem jmAddLeave;
    private javax.swing.JMenuItem jmAddStudent;
    private javax.swing.JMenuItem jmDisplayAccount;
    private javax.swing.JMenuItem jmDisplayEmployee;
    private javax.swing.JMenu jmEdit;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenuBar jmenuBar;
    // End of variables declaration//GEN-END:variables
    
}
