/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.student;

import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import publics.student.DBStudent;

import publics.student.Student;

import publics.student.Department;
import ui.GUI;

/**
 *
 * @author jpainam
 */
public class AddStudentForm extends javax.swing.JPanel {

    /**
     * Creates new form AddStudentForm
     */
    public AddStudentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeDetailsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcDepartment = new javax.swing.JComboBox();
        jtMatric = new javax.swing.JTextField();
        jtFirstName = new javax.swing.JTextField();
        jtLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtAddress = new javax.swing.JTextField();
        jtTelephon = new javax.swing.JTextField();
        jxDateBirth = new org.jdesktop.swingx.JXDatePicker();
        jcSex = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jtmiddlename = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtparentNo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtParent = new javax.swing.JTextField();
        warningPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jbValidate = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jbReset = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(813, 473));

        employeeDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Student Details"));

        jLabel1.setText("Matric No");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Department");

        jcDepartment.setModel(new DefaultComboBoxModel(publics.student.DBDepartment.getData().toArray()));

        jtMatric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMatricActionPerformed(evt);
            }
        });

        jLabel5.setText("Address");

        jLabel6.setText("Phone N°");

        jLabel7.setText("Date of birth");

        jLabel8.setText("Sex");

        jcSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel14.setText("Middle Name");

        jLabel15.setText("Parent N°");

        jLabel16.setText("Parent's Name");

        javax.swing.GroupLayout employeeDetailsPanelLayout = new javax.swing.GroupLayout(employeeDetailsPanel);
        employeeDetailsPanel.setLayout(employeeDetailsPanelLayout);
        employeeDetailsPanelLayout.setHorizontalGroup(
            employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                        .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14))
                        .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jtMatric, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtFirstName, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jtmiddlename)))
                        .addGap(37, 37, 37)
                        .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jxDateBirth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtTelephon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtparentNo))
                                .addGap(35, 35, 35))
                            .addComponent(jtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeDetailsPanelLayout.createSequentialGroup()
                        .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, employeeDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(23, 23, 23)
                                .addComponent(jcDepartment, 0, 214, Short.MAX_VALUE)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jcSex, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, employeeDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtParent)))
                        .addGap(64, 64, 64))))
        );

        employeeDetailsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtAddress, jtTelephon});

        employeeDetailsPanelLayout.setVerticalGroup(
            employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtMatric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtTelephon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jtparentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtmiddlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jxDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jcSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(24, 24, 24))
        );

        warningPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout warningPanelLayout = new javax.swing.GroupLayout(warningPanel);
        warningPanel.setLayout(warningPanelLayout);
        warningPanelLayout.setHorizontalGroup(
            warningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        warningPanelLayout.setVerticalGroup(
            warningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel9.setBackground(new java.awt.Color(222, 144, 144));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 160, 123));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ADD NEW STUDENT FORM");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jbValidate.setText("Submit");
        jbValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbValidateActionPerformed(evt);
            }
        });

        jbCancel.setText("Cancel");

        jbReset.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jbCancel)
                        .addGap(231, 231, 231)
                        .addComponent(jbReset)
                        .addGap(174, 174, 174)
                        .addComponent(jbValidate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(warningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeeDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancel)
                    .addComponent(jbValidate)
                    .addComponent(jbReset))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private String getMatric() {
        if (!this.jtMatric.getText().isEmpty()) {
            return this.jtMatric.getText();
        }
        return "";
    }

    private String getFirstName() {
        if (!this.jtFirstName.getText().isEmpty()) {
            return this.jtFirstName.getText();
        } else {
            return "";
        }
    }

    private String getLastName() {
        if (!this.jtLastName.getText().isEmpty()) {
            return this.jtLastName.getText();
        } else {
            return "";
        }
    }

    private Date getDob() {
        String entree = getSqlDob();
        if (entree.isEmpty()) {
            return new Date(0);
        } else {
            String[] st = entree.split("-");
            Calendar cal = Calendar.getInstance();
            //JOptionPane.showMessageDialog(null, st[0] + " " + st[1] + " " + st[2]);
            cal.set(Integer.parseInt(st[0]), Integer.parseInt(st[1]) - 1, Integer.parseInt(st[2]));
            Date d = new Date(cal.getTimeInMillis());
            //JOptionPane.showConfirmDialog(null, d.toString());
            return d;
        }
    }

    /**
     *
     * @return the date of birth in the SQL format
     */
    public String getSqlDob() {
        DateFormat dateFormat = new SimpleDateFormat("E dd/MM/yyyy");
        jxDateBirth.setFormats(dateFormat);
        DateFormat sysDate = new SimpleDateFormat("yyyy-MM-dd");
        if(jxDateBirth.getDate() == null)
            jxDateBirth.setDate(new Date(Calendar.getInstance().getTimeInMillis()));
        String date_to_store = sysDate.format(jxDateBirth.getDate()).toString();
        return date_to_store;
    }

    private Department getDepartment() {
        Object obj = jcDepartment.getSelectedItem();
        if (obj instanceof Department) {
            Department depart = (Department) obj;
            return depart;
        }
        return null;
    }

    private String getAddress() {
        if (!this.jtAddress.getText().isEmpty()) {
            return jtAddress.getText();
        } else {
            return "";
        }
    }

    private String getPhone() {
        if (!jtTelephon.getText().isEmpty()) {
            return jtTelephon.getText();
        }
        return "";
    }

    private String getSex() {
        return jcSex.getSelectedItem().toString();
    }

    private String getMiddleName() {
        if (!jtmiddlename.getText().isEmpty()) {
            return this.jtmiddlename.getText();
        } else {
            return new String();
        }
    }

    private String getParentNo() {
        if (!jtparentNo.getText().isEmpty()) {
            return jtparentNo.getText();
        } else {
            return new String();
        }
    }

    public String getInfoParent() {
        if (jtParent.getText().isEmpty()) {
            return jtParent.getText();
        } else {
            return new String();
        }
    }
    /*
     *Student(int id, String matric, String fname, String lname,
     String mname, String sex, Date dob, String address,
     String phone, String parentno, String parent, Department depart) {
     */
    private void jbValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbValidateActionPerformed

        Student stud = new Student(new Integer(1), getMatric(), getFirstName(),
                getLastName(), getMiddleName(), getSex(), getDob(),
                getAddress(), getPhone(), getParentNo(), this.getInfoParent(),
                getDepartment());
        /* Send the Student to the database */
        if (DBStudent.storeData(stud)) {
            JOptionPane.showMessageDialog(null, "Student inserted with success!!!");
            try {
                GUI.getInstance().getContentPane().removeAll();
                GUI.getInstance().setContentPane(new DisplayStudent());
                GUI.getInstance().repaint();
                GUI.getInstance().pack();
            } catch (IllegalStateException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error in inserting the employee");
        }

    }//GEN-LAST:event_jbValidateActionPerformed

    private void jtMatricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMatricActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMatricActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel employeeDetailsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbReset;
    private javax.swing.JButton jbValidate;
    private javax.swing.JComboBox jcDepartment;
    private javax.swing.JComboBox jcSex;
    private javax.swing.JTextField jtAddress;
    private javax.swing.JTextField jtFirstName;
    private javax.swing.JTextField jtLastName;
    private javax.swing.JTextField jtMatric;
    private javax.swing.JTextField jtParent;
    private javax.swing.JTextField jtTelephon;
    private javax.swing.JTextField jtmiddlename;
    private javax.swing.JTextField jtparentNo;
    private org.jdesktop.swingx.JXDatePicker jxDateBirth;
    private javax.swing.JPanel warningPanel;
    // End of variables declaration//GEN-END:variables
}
