/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.garment;

import publics.student.StudentJTable;

/**
 *
 * @author jpainam
 */
public class DetailsGarment extends javax.swing.JPanel {

    /**
     * Creates new form DetailsGarment
     */
    public DetailsGarment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jpanneau1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jscrollListeEmployeeGarment = new javax.swing.JScrollPane();
        jpanneau2 = new javax.swing.JPanel();

        jLabel9.setBackground(new java.awt.Color(222, 144, 144));
        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 160, 123));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DETAILS OF GARMENT");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setDividerSize(3);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(256, 25));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("List of employee appointed to the garment");

        jscrollListeEmployeeGarment.setViewportView(table);

        javax.swing.GroupLayout jpanneau1Layout = new javax.swing.GroupLayout(jpanneau1);
        jpanneau1.setLayout(jpanneau1Layout);
        jpanneau1Layout.setHorizontalGroup(
            jpanneau1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanneau1Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanneau1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscrollListeEmployeeGarment)
                .addContainerGap())
        );
        jpanneau1Layout.setVerticalGroup(
            jpanneau1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanneau1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscrollListeEmployeeGarment, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jpanneau1);

        javax.swing.GroupLayout jpanneau2Layout = new javax.swing.GroupLayout(jpanneau2);
        jpanneau2.setLayout(jpanneau2Layout);
        jpanneau2Layout.setHorizontalGroup(
            jpanneau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );
        jpanneau2Layout.setVerticalGroup(
            jpanneau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jpanneau2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(429, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel jpanneau1;
    private javax.swing.JPanel jpanneau2;
    private javax.swing.JScrollPane jscrollListeEmployeeGarment;
    // End of variables declaration//GEN-END:variables
    private StudentJTable table = new StudentJTable(0);
}
