/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.garment;

import ui.employee.DisplayEmployee;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import publics.RowHeadersRenderer;
import publics.garment.DBGarment;
import publics.garment.Garment;
import publics.garment.GarmentJTable;
import publics.garment.GarmentJTableModel;
import ui.GUI;

/**
 *
 * @author jpainam
 */
public class DisplayGarment extends javax.swing.JPanel {

    /**
     * Creates new form DisplayGarment
     */
    public DisplayGarment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtSearchGarment = new javax.swing.JTextField();
        jbSearchGarment = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbEditGarment = new javax.swing.JButton();
        jbDeleteGarment = new javax.swing.JButton();
        jbDetailsGarment = new javax.swing.JButton();
        jscrollTableGarment = new javax.swing.JScrollPane();

        jLabel9.setBackground(new java.awt.Color(222, 144, 144));
        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 160, 123));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("LIST OF GARMENTS");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Table of employee"));

        jLabel1.setText("Search for an employee");

        jbSearchGarment.setText("Search");
        jbSearchGarment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchGarmentActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jbEditGarment.setText("Edit");
        jbEditGarment.setToolTipText("Edit the selected Employee");
        jbEditGarment.setEnabled(false);
        jbEditGarment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditGarmentActionPerformed(evt);
            }
        });

        jbDeleteGarment.setText("Delete");
        jbDeleteGarment.setToolTipText("Delete the selected Employee");
        jbDeleteGarment.setEnabled(false);
        jbDeleteGarment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteGarmentActionPerformed(evt);
            }
        });

        jbDetailsGarment.setText("Details");
        jbDetailsGarment.setToolTipText("Find more details on the selected Employee");
        jbDetailsGarment.setEnabled(false);
        jbDetailsGarment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDetailsGarmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jbEditGarment, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jbDeleteGarment, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbDetailsGarment, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbEditGarment)
                .addComponent(jbDeleteGarment)
                .addComponent(jbDetailsGarment))
        );

        table.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                tableValueChanged(e);
            }
        });
        jscrollTableGarment.setViewportView(table);
        jscrollTableGarment.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jscrollTableGarment)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtSearchGarment, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbSearchGarment, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(390, 390, 390))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtSearchGarment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSearchGarment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscrollTableGarment, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbSearchGarmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchGarmentActionPerformed
        ArrayList<Garment> employee;
        employee = (ArrayList<Garment>) DBGarment.searchGarment(jtSearchGarment.getText());
        table.removeAll();
        table.setModel(new GarmentJTableModel(employee));
        /** Reapply the JTableModel */
        table.getColumnModel().getColumn(0).setHeaderValue("N°");
        table.getColumnModel().getColumn(0).setPreferredWidth(0x2);
        table.getColumnModel().getColumn(0).setWidth(0x2);
        Dimension d = table.getPreferredScrollableViewportSize();
        d.width = getPreferredSize().width;
        table.setPreferredScrollableViewportSize(d);
        table.setRowHeight(table.getRowHeight());
        RowHeadersRenderer rowRenderer = new RowHeadersRenderer();
        //gridStudent.setDefaultRenderer(String.class, rowRenderer); // This does not work
        table.getColumnModel().getColumn(0).setCellRenderer(rowRenderer);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }//GEN-LAST:event_jbSearchGarmentActionPerformed
    private String getId(){
        int row = table.getSelectedRow();
        return table.getValueAt(row, 1).toString();
    }
    /**
     * Launch the Edit Panel used to edit the Garment
     * @param evt 
     */
    private void jbEditGarmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditGarmentActionPerformed
        String ssn = getId();
        GUI g = GUI.getInstance();
        g.getContentPane().removeAll();
        g.setContentPane(new EditGarment(DBGarment.getData(ssn)));
        g.repaint();
        g.pack();

    }//GEN-LAST:event_jbEditGarmentActionPerformed

    private void jbDeleteGarmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteGarmentActionPerformed
        if(DBGarment.deleteData(getId())){
            JOptionPane.showMessageDialog(null, "Garment deleted with success");
            /* Retirer une ligne du tableau quand supprimer est ok */
            //table.updateUI();
            GUI g = GUI.getInstance();
            g.getContentPane().removeAll();
            g.setContentPane(new DisplayEmployee());
            g.repaint();
            g.pack();
        }else{
            JOptionPane.showMessageDialog(null, "Error in deleting the garment");
        }
    }//GEN-LAST:event_jbDeleteGarmentActionPerformed

    private void jbDetailsGarmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDetailsGarmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbDetailsGarmentActionPerformed
    private  void tableValueChanged(ListSelectionEvent e){
        if(table.getSelectedRow()  >= 0){
            jbDeleteGarment.setEnabled(true);
            jbEditGarment.setEnabled(true);
            jbDetailsGarment.setEnabled(true);
        }else{
            jbDeleteGarment.setEnabled(false);
            jbEditGarment.setEnabled(false);
            jbDetailsGarment.setEnabled(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbDeleteGarment;
    private javax.swing.JButton jbDetailsGarment;
    private javax.swing.JButton jbEditGarment;
    private javax.swing.JButton jbSearchGarment;
    private javax.swing.JScrollPane jscrollTableGarment;
    private javax.swing.JTextField jtSearchGarment;
    // End of variables declaration//GEN-END:variables
    private GarmentJTable table = new GarmentJTable();
}
